### PR TITLE
Feature/recipe preview

### PR DESCRIPTION
**Pull request by codespace-justin**
Same thing as yesterday's PR:

- resolves merge conflict
- updates recipe-items.js
- accepts incoming change from main as the jsx had more features and was more up to date

### CODE REVIEW

**Review by OlebogengBogopane — APPROVED** [review]
Approved... code checks

**Review by Dremas22 — APPROVED** [review]
Approved

**Comment by Dremas22** [comment]
Adds view recipes button on recipe-list file

**Comment by Dremas22** [comment]
Adds view recipe button on recipe-list.js and recipe-items.css

**Pull request merged**
