### PR TITLE
Backup main

### PR DESCRIPTION
**Pull request by OlebogengKhunou**
update the routing functionalities

### CODE REVIEW

**Review by Dremas22 — APPROVED** [review]
I approve the changes

**Review by OlebogengBogopane — APPROVED** [review]
Adds Pagination routing to main... code Approved

**Review by Oteng29 — APPROVED** [review]
Code checks

**Comment by codespace-justin** [comment]
@OlebogengKhunou   @OlebogengBogopane Hey guys, just curious as to what is happening with this branch, why this branch has features on it, and why you would like to merge this into main instead of merging the feature itself into main.

I thought this was just supposed to be a backup of the main branch.

Please provide some insight since im a bit confused.

**Comment by OlebogengBogopane** [comment]
@codespace-justin We used the backup as our feature  for the last major change to restructure the page files for routing on main branch also considering we are finishing epic one and we may need to create new branches on the next epic

**Pull request merged**
