### PR TITLE
Feature/filtering data

### PR DESCRIPTION
**Pull request by Dremas22**
Adds runUpdateInstructions function on data.js, udatingInstruction folder and updatingInstructions.js

### CODE REVIEW

**Review by Oteng29 — APPROVED** [review]

**Review by OlebogengBogopane — APPROVED** [review]
Approved... update instructions inside API folder

**Review by OlebogengRasebitse — APPROVED** [review]
Looks good

**Review by Oteng29 — APPROVED** [review]
Approved

**Comment by Dremas22** [comment]
due to vercel failure

**Pull request closed without merging**
