### PR TITLE
Feature/recipe preview

### PR DESCRIPTION
**Pull request by Dremas22**
Updating my branch with main

### CODE REVIEW

**Review by OlebogengBogopane — APPROVED** [review]
Approved...

**Review by codespace-justin — APPROVED** [review]
@Dremas22 Your code still has the merge conflict but ill resolve it for you locally. Please pay more attention in future when comparing incoming changes from the main branch and the code that is on your feature branch.

When it comes to installing dependancies, altering configuration files, or shared files such the main.css or app.js, please consult your group lead first, or speak with the team members responsible for that feature and have them make the changes, or at least notify them that you are changing code shared across the team.

Thanks.

**Review by codespace-justin — DISMISSED** [review]
Accepted incoming changes from main since it had the same code with more features written by other team members.

**Review by OlebogengBogopane — DISMISSED** [review]
Approved

**Review by codespace-justin — DISMISSED** [review]

**Comment by codespace-justin** [comment]
Closing off this pull request since its creating bugs for reason. In future @Dremas22 or if any one does not know how to resolve their merge conflicts let me know and we can debug it as an example during standup.

**Pull request closed without merging**
